apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-eta-deploy
  labels:
    app: insurance-eta-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: insurance-eta-app
  template:
    metadata:
      labels:
        app: insurance-eta-app
    spec:
      containers:
      - name: insurance-eta-container
        image: waasifahmed/insurance-eta-app
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: insurance-eta-np-service
  labels:
    app: insurance-eta-app
spec:
  selector:
    app: insurance-eta-app

  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
